Added a cactus prefab that can hurt the player
boreal1s/goat-galaxy-games pull request #58
Opened 2024-11-25 05:01 UTC by SaharNikkhah

2024-11-25 07:57 UTC, heostar requested changes
This worked for me, but can you place these in the map ?

2024-11-26 06:15 UTC, thedanhle approved these changes
Looks good!

2024-11-26 07:05 UTC, thedanhle approved these changes

2024-11-26 07:06 UTC, heostar approved these changes

2024-11-26 07:06 UTC, merged